const sampleProducts = [
  // --- BOOKS & STUDY MATERIAL ---
  {
    title: "Engineering Mechanics - Shivakumar",
    description: "1st Year Mechanical Engineering textbook. Good condition, highlighted important points.",
    price: 350,
    category: "Books",
    condition: "Good",
    college: "UIT RGPV",
    location: "UIT Circle",
    images: [{ url: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?q=80&w=800&auto=format&fit=crop", filename: "book_mech" }],
  },
  {
    title: "Handwritten C++ Notes",
    description: "Complete CS semester 3 notes. Very neat handwriting.",
    price: 100,
    category: "Books",
    condition: "New",
    college: "UIT RGPV",
    location: "UIT Circle",
    images: [{ url: "https://images.unsplash.com/photo-1456735190827-d1262f71b8a6?q=80&w=800&auto=format&fit=crop", filename: "notes" }],
  },
  {
    title: "Mathematics-I (B.S. Grewal)",
    description: "Standard engineering math book. Hardcover, slightly worn out edges.",
    price: 450,
    category: "Books",
    condition: "Fair",
    college: "UIT RGPV",
    location: "UIT Circle",
    images: [{ url: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?q=80&w=800&auto=format&fit=crop", filename: "math_book" }],
  },
  {
    title: "Python Programming - Black Book",
    description: "Comprehensive guide for Python. Like new, barely used.",
    price: 500,
    category: "Books",
    condition: "Like New",
    college: "UIT RGPV",
    location: "UIT Circle",
    images: [{ url: "https://images.unsplash.com/photo-1526379095098-d400fd0bf935?q=80&w=800&auto=format&fit=crop", filename: "python_book" }],
  },
  {
    title: "Electrical Engineering Fundamentals",
    description: "Basic Electrical Engineering (BEE) textbook. Useful for 1st year.",
    price: 300,
    category: "Books",
    condition: "Good",
    college: "UIT RGPV",
    location: "UIT Circle",
    images: [{ url: "https://images.unsplash.com/photo-1532012197267-da84d127e765?q=80&w=800&auto=format&fit=crop", filename: "bee_book" }],
  },
  {
    title: "Fiction Novels Bundle",
    description: "Set of 3 novels: Alchemist, Kite Runner, Life of Pi. Great for leisure reading.",
    price: 400,
    category: "Books",
    condition: "Good",
    college: "UIT RGPV",
    location: "UIT Circle",
    images: [{ url: "https://images.unsplash.com/photo-1512820790803-83ca734da794?q=80&w=800&auto=format&fit=crop", filename: "novels" }],
  },

  // --- STATIONERY ---
  {
    title: "Casio Scientific Calculator",
    description: "FX-991EX. Essential for exams. Used for 1 semester only.",
    price: 850,
    category: "Stationery",
    condition: "Like New",
    college: "UIT RGPV",
    location: "UIT Circle",
    images: [{ url: "https://images.unsplash.com/photo-1594910619397-6577382d622c?q=80&w=800&auto=format&fit=crop", filename: "calc" }],
  },
  {
    title: "Engineering Drafter (Omega)",
    description: "Mini drafter with scale. working perfectly. Required for ED labs.",
    price: 400,
    category: "Stationery",
    condition: "Fair",
    college: "UIT RGPV",
    location: "UIT Circle",
    images: [{ url: "https://plus.unsplash.com/premium_photo-1664302152996-5e26b1757881?q=80&w=800&auto=format&fit=crop", filename: "drafter" }],
  },
  {
    title: "Geometry Box - Classmate",
    description: "Full geometry set. Compass, divider, protractor all included.",
    price: 100,
    category: "Stationery",
    condition: "Good",
    college: "UIT RGPV",
    location: "UIT Circle",
    images: [{ url: "https://images.unsplash.com/photo-1597484662317-c931045f8f5e?q=80&w=800&auto=format&fit=crop", filename: "geometry" }],
  },
  {
    title: "A3 Drawing Sheet Holder",
    description: "Plastic roll container for engineering drawing sheets. Keeps sheets safe from rain.",
    price: 150,
    category: "Stationery",
    condition: "Good",
    college: "UIT RGPV",
    location: "UIT Circle",
    images: [{ url: "https://images.unsplash.com/photo-1513346940221-18f4601d88ce?q=80&w=800&auto=format&fit=crop", filename: "sheet_holder" }],
  },
  {
    title: "Spiral Notebooks (Unused)",
    description: "Pack of 3 unruled spiral notebooks. Bought extra, not needed now.",
    price: 120,
    category: "Stationery",
    condition: "New",
    college: "UIT RGPV",
    location: "UIT Circle",
    images: [{ url: "https://images.unsplash.com/photo-1531346878377-a513bc95f87b?q=80&w=800&auto=format&fit=crop", filename: "notebooks" }],
  },

  // --- ELECTRONICS ---
  {
    title: "Extension Cord",
    description: "3 sockets with 2 USB ports. Very useful for hostel rooms.",
    price: 350,
    category: "Electronics",
    condition: "Like New",
    college: "UIT RGPV",
    location: "UIT Circle",
    images: [{ url: "https://images.unsplash.com/photo-1554160456-11f879684534?q=80&w=800&auto=format&fit=crop", filename: "extension" }],
  },
  {
    title: "Wireless Mouse - Logitech",
    description: "Basic wireless mouse M170. Battery included. Works perfectly.",
    price: 450,
    category: "Electronics",
    condition: "Good",
    college: "UIT RGPV",
    location: "UIT Circle",
    images: [{ url: "https://images.unsplash.com/photo-1615663245857-acda5b2b15d5?q=80&w=800&auto=format&fit=crop", filename: "mouse" }],
  },
  {
    title: "USB Pendrive 32GB",
    description: "Sandisk Cruzer Blade. Formatted and empty.",
    price: 250,
    category: "Electronics",
    condition: "Good",
    college: "UIT RGPV",
    location: "UIT Circle",
    images: [{ url: "https://images.unsplash.com/photo-1623949901862-388144d6b7f3?q=80&w=800&auto=format&fit=crop", filename: "pendrive" }],
  },
  {
    title: "Laptop Cooling Pad",
    description: "Single fan cooling pad, USB powered. Helps while gaming.",
    price: 600,
    category: "Electronics",
    condition: "Fair",
    college: "UIT RGPV",
    location: "UIT Circle",
    images: [{ url: "https://images.unsplash.com/photo-1618418342749-0d321151667d?q=80&w=800&auto=format&fit=crop", filename: "coolingpad" }],
  },
  {
    title: "Earphones (Wired)",
    description: "Boat Bassheads 100. New in box, never opened.",
    price: 350,
    category: "Electronics",
    condition: "New",
    college: "UIT RGPV",
    location: "UIT Circle",
    images: [{ url: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?q=80&w=800&auto=format&fit=crop", filename: "earphones" }],
  },

  // --- HOSTEL & FURNITURE ---
  {
    title: "Study Table Lamp",
    description: "Small LED lamp, USB rechargeable. Perfect for hostel study.",
    price: 300,
    category: "Furniture",
    condition: "Good",
    college: "UIT RGPV",
    location: "UIT Circle",
    images: [{ url: "https://images.unsplash.com/photo-1533230678685-6e42b291d37b?q=80&w=800&auto=format&fit=crop", filename: "lamp" }],
  },
  {
    title: "Hostel Mattress (Single)",
    description: "Foam mattress for single bed. 3 inches thick. Clean cover included.",
    price: 900,
    category: "Furniture",
    condition: "Fair",
    college: "UIT RGPV",
    location: "UIT Circle",
    images: [{ url: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?q=80&w=800&auto=format&fit=crop", filename: "mattress" }],
  },
  {
    title: "Plastic Chair",
    description: "Nilkamal chair, sturdy. Red color.",
    price: 400,
    category: "Furniture",
    condition: "Good",
    college: "UIT RGPV",
    location: "UIT Circle",
    images: [{ url: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=800&auto=format&fit=crop", filename: "chair" }],
  },
  {
    title: "Small Foldable Table",
    description: "Bed table for laptop or eating. Wooden finish.",
    price: 350,
    category: "Furniture",
    condition: "Good",
    college: "UIT RGPV",
    location: "UIT Circle",
    images: [{ url: "https://images.unsplash.com/photo-1622396362244-67252278b7b2?q=80&w=800&auto=format&fit=crop", filename: "bedtable" }],
  },
  {
    title: "Cloth Drying Stand",
    description: "Metal stand, foldable. Fits in balcony.",
    price: 800,
    category: "Furniture",
    condition: "Fair",
    college: "UIT RGPV",
    location: "UIT Circle",
    images: [{ url: "https://images.unsplash.com/photo-1473445361085-b5a8c544fa0e?q=80&w=800&auto=format&fit=crop", filename: "dryingstand" }],
  },

  // --- CLOTHING & ACCESSORIES ---
  {
    title: "Chemistry Lab Coat",
    description: "White cotton lab coat, size L. Clean and washed.",
    price: 250,
    category: "Clothing",
    condition: "Good",
    college: "UIT RGPV",
    location: "UIT Circle",
    images: [{ url: "https://images.unsplash.com/photo-1584036561566-b45274d5da33?q=80&w=800&auto=format&fit=crop", filename: "labcoat" }],
  },
  {
    title: "College Hoodie (Grey)",
    description: "Size XL. Warm hoodie, barely worn.",
    price: 500,
    category: "Clothing",
    condition: "Like New",
    college: "UIT RGPV",
    location: "UIT Circle",
    images: [{ url: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?q=80&w=800&auto=format&fit=crop", filename: "hoodie" }],
  },
  {
    title: "Formal Shirt (White)",
    description: "Size 40. Required for interviews/presentations. Worn once.",
    price: 400,
    category: "Clothing",
    condition: "Like New",
    college: "UIT RGPV",
    location: "UIT Circle",
    images: [{ url: "https://images.unsplash.com/photo-1603252109303-27514432f5e3?q=80&w=800&auto=format&fit=crop", filename: "shirt" }],
  },

  // --- SPORTS ---
  {
    title: "Badminton Racket",
    description: "Basic racket for casual play in evening. Gutting is intact.",
    price: 600,
    category: "Sports",
    condition: "Fair",
    college: "UIT RGPV",
    location: "UIT Circle",
    images: [{ url: "https://images.unsplash.com/photo-1626224583764-84786c71973e?q=80&w=800&auto=format&fit=crop", filename: "racket" }],
  },
  {
    title: "Cricket Bat (Tennis Ball)",
    description: "Kashmir willow bat. Good stroke. Handle grip needs replacement.",
    price: 700,
    category: "Sports",
    condition: "Good",
    college: "UIT RGPV",
    location: "UIT Circle",
    images: [{ url: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?q=80&w=800&auto=format&fit=crop", filename: "bat" }],
  },
  {
    title: "Yoga Mat",
    description: "6mm thickness. Anti-slip. Blue color.",
    price: 350,
    category: "Sports",
    condition: "Good",
    college: "UIT RGPV",
    location: "UIT Circle",
    images: [{ url: "https://images.unsplash.com/photo-1592432678016-e910b452f9a9?q=80&w=800&auto=format&fit=crop", filename: "yogamat" }],
  },
  {
    title: "Football (Nivia)",
    description: "Standard size 5 football. Good for ground practice.",
    price: 450,
    category: "Sports",
    condition: "Fair",
    college: "UIT RGPV",
    location: "UIT Circle",
    images: [{ url: "https://images.unsplash.com/photo-1614632537423-1e6c2e7e0aab?q=80&w=800&auto=format&fit=crop", filename: "football" }],
  },

  // --- OTHER ---
  {
    title: "Water Bottle (Steel)",
    description: "Milton 1 Litre bottle. Keeps water cool for 5 hours.",
    price: 200,
    category: "Other",
    condition: "Good",
    college: "UIT RGPV",
    location: "UIT Circle",
    images: [{ url: "https://images.unsplash.com/photo-1602143407151-11115cd4e69b?q=80&w=800&auto=format&fit=crop", filename: "bottle" }],
  },
  {
    title: "Laundry Bag",
    description: "Mesh laundry bag. Foldable and washable.",
    price: 150,
    category: "Other",
    condition: "New",
    college: "UIT RGPV",
    location: "UIT Circle",
    images: [{ url: "https://images.unsplash.com/photo-1582735689369-4fe89db7114c?q=80&w=800&auto=format&fit=crop", filename: "laundrybag" }],
  },
  {
    title: "Electric Kettle (0.5L)",
    description: "Small kettle for boiling water/making maggi. Working fine.",
    price: 550,
    category: "Other",
    condition: "Good",
    college: "UIT RGPV",
    location: "UIT Circle",
    images: [{ url: "https://images.unsplash.com/photo-1594213114663-d94db9b17126?q=80&w=800&auto=format&fit=crop", filename: "kettle" }],
  },
  {
    title: "Bucket and Mug Set",
    description: "Blue plastic bucket (15L) and mug. Essential for hostel bathroom.",
    price: 200,
    category: "Other",
    condition: "New",
    college: "UIT RGPV",
    location: "UIT Circle",
    images: [{ url: "https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?q=80&w=800&auto=format&fit=crop", filename: "bucket" }],
  }
];

module.exports = { data: sampleProducts };